version: '3.9'

services:
  web:
    build:
      context: ./locallibrary
      dockerfile: Dockerfile.prod
    command: gunicorn locallibrary.wsgi:application --bind 0.0.0.0:9000
    volumes:
      - static_volume:/home/locallibrary/web/staticfiles
      - media_volume:/home/locallibrary/web/mediafiles
    expose:
      - 9000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/locallibrary/web/staticfiles
      - media_volume:/home/locallibrary/web/mediafiles
    ports:
      - 5000:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
